//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuratorHelper.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CuratorHelper.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Успешно добавлено!.
        /// </summary>
        public static string AddCongrats {
            get {
                return ResourceManager.GetString("AddCongrats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить курсовую работу.
        /// </summary>
        public static string AddCourseWork {
            get {
                return ResourceManager.GetString("AddCourseWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить результат демо.
        /// </summary>
        public static string AddDemoExam {
            get {
                return ResourceManager.GetString("AddDemoExam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить название демо.
        /// </summary>
        public static string AddDemoExamName {
            get {
                return ResourceManager.GetString("AddDemoExamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить дисциплину.
        /// </summary>
        public static string AddDiscipline {
            get {
                return ResourceManager.GetString("AddDiscipline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить/изменить.
        /// </summary>
        public static string AddEdit {
            get {
                return ResourceManager.GetString("AddEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить ВКР.
        /// </summary>
        public static string AddGraduateWork {
            get {
                return ResourceManager.GetString("AddGraduateWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить группу.
        /// </summary>
        public static string AddGroup {
            get {
                return ResourceManager.GetString("AddGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить предмет.
        /// </summary>
        public static string AddObject {
            get {
                return ResourceManager.GetString("AddObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить практику.
        /// </summary>
        public static string AddPractice {
            get {
                return ResourceManager.GetString("AddPractice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить название практики.
        /// </summary>
        public static string AddPracticeName {
            get {
                return ResourceManager.GetString("AddPracticeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить квалификацию.
        /// </summary>
        public static string AddQualification {
            get {
                return ResourceManager.GetString("AddQualification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить студента.
        /// </summary>
        public static string AddStudent {
            get {
                return ResourceManager.GetString("AddStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить/изменить оценки.
        /// </summary>
        public static string AddStudentMarks {
            get {
                return ResourceManager.GetString("AddStudentMarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить/изменить пропуски.
        /// </summary>
        public static string AddStudentOmissions {
            get {
                return ResourceManager.GetString("AddStudentOmissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить поощрение/взыскание.
        /// </summary>
        public static string AddStudentPenAndInc {
            get {
                return ResourceManager.GetString("AddStudentPenAndInc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить преподавателя.
        /// </summary>
        public static string AddTeacher {
            get {
                return ResourceManager.GetString("AddTeacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Направлен на работу (учебу).
        /// </summary>
        public static string AimedAt {
            get {
                return ResourceManager.GetString("AimedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уверены, что хотите удалить?.
        /// </summary>
        public static string AreYouSureDelete {
            get {
                return ResourceManager.GetString("AreYouSureDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Авторизация.
        /// </summary>
        public static string Authorization {
            get {
                return ResourceManager.GetString("Authorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата рождения.
        /// </summary>
        public static string Birthdate {
            get {
                return ResourceManager.GetString("Birthdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбрать дату рождения.
        /// </summary>
        public static string BirthdateToolTip {
            get {
                return ResourceManager.GetString("BirthdateToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Место рождения.
        /// </summary>
        public static string BirthPlace {
            get {
                return ResourceManager.GetString("BirthPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Общественная работа.
        /// </summary>
        public static string CommunityService {
            get {
                return ResourceManager.GetString("CommunityService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На базе классов.
        /// </summary>
        public static string CompletedClasses {
            get {
                return ResourceManager.GetString("CompletedClasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Курс.
        /// </summary>
        public static string Course {
            get {
                return ResourceManager.GetString("Course", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверьте наличие курсовой с похожей/иной темой по данной дисциплине и семестру.
        /// </summary>
        public static string CourseWorkExists {
            get {
                return ResourceManager.GetString("CourseWorkExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Курсовые работы.
        /// </summary>
        public static string CourseWorks {
            get {
                return ResourceManager.GetString("CourseWorks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы не выбрали курсовые работы.
        /// </summary>
        public static string CourseWorksCountZero {
            get {
                return ResourceManager.GetString("CourseWorksCountZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать приказ.
        /// </summary>
        public static string CreateOrder {
            get {
                return ResourceManager.GetString("CreateOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Куратор.
        /// </summary>
        public static string Curator {
            get {
                return ResourceManager.GetString("Curator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помощник куратора.
        /// </summary>
        public static string CuratorHelper {
            get {
                return ResourceManager.GetString("CuratorHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текущий куратор.
        /// </summary>
        public static string CurCurator {
            get {
                return ResourceManager.GetString("CurCurator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Соединение с БД не установлено. Проверьте наличие БД в MSSQL, а также строку подключения.
        /// </summary>
        public static string DatabaseError {
            get {
                return ResourceManager.GetString("DatabaseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продолжительность.
        /// </summary>
        public static string DaysDuration {
            get {
                return ResourceManager.GetString("DaysDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверьте правильность продолжительности практики.
        /// </summary>
        public static string DaysDurationError {
            get {
                return ResourceManager.GetString("DaysDurationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Результат за этот демо уже выставлен.
        /// </summary>
        public static string DemoExamExists {
            get {
                return ResourceManager.GetString("DemoExamExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Такое название уже существует.
        /// </summary>
        public static string DemoExamNameExists {
            get {
                return ResourceManager.GetString("DemoExamNameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Демо-экзамены.
        /// </summary>
        public static string DemoExams {
            get {
                return ResourceManager.GetString("DemoExams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отделение.
        /// </summary>
        public static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дисциплина.
        /// </summary>
        public static string Discipline {
            get {
                return ResourceManager.GetString("Discipline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Такая дисциплина уже существует.
        /// </summary>
        public static string DisciplineExists {
            get {
                return ResourceManager.GetString("DisciplineExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы не выбрали дисциплины.
        /// </summary>
        public static string DisciplinesCountZero {
            get {
                return ResourceManager.GetString("DisciplinesCountZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверьте наличие выставленных по дисциплинам оценок в семестре, а также количество дисциплин.
        /// </summary>
        public static string DisciplinesError {
            get {
                return ResourceManager.GetString("DisciplinesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить прикрепленных преподавателей.
        /// </summary>
        public static string EditAppointedTeachers {
            get {
                return ResourceManager.GetString("EditAppointedTeachers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Успешно изменено.
        /// </summary>
        public static string EditCongrats {
            get {
                return ResourceManager.GetString("EditCongrats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить текущего куратора группы.
        /// </summary>
        public static string EditCurCurator {
            get {
                return ResourceManager.GetString("EditCurCurator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактирование информации.
        /// </summary>
        public static string EditInfo {
            get {
                return ResourceManager.GetString("EditInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить предметы.
        /// </summary>
        public static string EditObjects {
            get {
                return ResourceManager.GetString("EditObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить преподаваемые предметы.
        /// </summary>
        public static string EditTeacherObjects {
            get {
                return ResourceManager.GetString("EditTeacherObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войти.
        /// </summary>
        public static string Enter {
            get {
                return ResourceManager.GetString("Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выход.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата сдачи.
        /// </summary>
        public static string FinishDate {
            get {
                return ResourceManager.GetString("FinishDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбрать дату сдачи.
        /// </summary>
        public static string FinishDateToolTip {
            get {
                return ResourceManager.GetString("FinishDateToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        public static string Firstname {
            get {
                return ResourceManager.GetString("Firstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сформировать.
        /// </summary>
        public static string Form {
            get {
                return ResourceManager.GetString("Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пол.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данный студент уже защитил ВКР.
        /// </summary>
        public static string GraduateWorkExists {
            get {
                return ResourceManager.GetString("GraduateWorkExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выпуск. квалиф. работы.
        /// </summary>
        public static string GraduateWorks {
            get {
                return ResourceManager.GetString("GraduateWorks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы не выбрали ВКР.
        /// </summary>
        public static string GraduateWorksCountZero {
            get {
                return ResourceManager.GetString("GraduateWorksCountZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Такая группа уже существует.
        /// </summary>
        public static string GroupExists {
            get {
                return ResourceManager.GetString("GroupExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название группы.
        /// </summary>
        public static string GroupName {
            get {
                return ResourceManager.GetString("GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Группы.
        /// </summary>
        public static string Groups {
            get {
                return ResourceManager.GetString("Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы не выбрали группу.
        /// </summary>
        public static string GroupsCountZero {
            get {
                return ResourceManager.GetString("GroupsCountZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адрес родителей (воспитателей).
        /// </summary>
        public static string GuardianAddress {
            get {
                return ResourceManager.GetString("GuardianAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вид выпускной квалификационной работы.
        /// </summary>
        public static string GWKType {
            get {
                return ResourceManager.GetString("GWKType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удаление невозможно, проверьте наличие любых связей.
        /// </summary>
        public static string HaveConnectionsError {
            get {
                return ResourceManager.GetString("HaveConnectionsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Индекс.
        /// </summary>
        public static string Index {
            get {
                return ResourceManager.GetString("Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Логин.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверно введен логин или пароль. Проверьте правильность ввода и повторите попытку..
        /// </summary>
        public static string LogOrPassError {
            get {
                return ResourceManager.GetString("LogOrPassError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Главное меню.
        /// </summary>
        public static string MainMenu {
            get {
                return ResourceManager.GetString("MainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оценка.
        /// </summary>
        public static string Mark {
            get {
                return ResourceManager.GetString("Mark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оценки.
        /// </summary>
        public static string Marks {
            get {
                return ResourceManager.GetString("Marks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы не выбрали оценки по дисциплинам на удаление.
        /// </summary>
        public static string MarksCountZero {
            get {
                return ResourceManager.GetString("MarksCountZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отчество.
        /// </summary>
        public static string Middlename {
            get {
                return ResourceManager.GetString("Middlename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мои группы.
        /// </summary>
        public static string MyGroups {
            get {
                return ResourceManager.GetString("MyGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Характер.
        /// </summary>
        public static string Nature {
            get {
                return ResourceManager.GetString("Nature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вам необходимо заполнить все обязательные поля.
        /// </summary>
        public static string NeedToFillRequired {
            get {
                return ResourceManager.GetString("NeedToFillRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы не выбрали предметы на удаление.
        /// </summary>
        public static string ObjectCountZero {
            get {
                return ResourceManager.GetString("ObjectCountZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предмет с таким названием уже существует.
        /// </summary>
        public static string ObjectExists {
            get {
                return ResourceManager.GetString("ObjectExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предметы и дисциплины.
        /// </summary>
        public static string ObjectsAndDisciplines {
            get {
                return ResourceManager.GetString("ObjectsAndDisciplines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество пропусков не может превышать количество учебных часов в семестре.
        /// </summary>
        public static string OmissionCountError {
            get {
                return ResourceManager.GetString("OmissionCountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пропуски.
        /// </summary>
        public static string Omissions {
            get {
                return ResourceManager.GetString("Omissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип пропуска.
        /// </summary>
        public static string OmissionType {
            get {
                return ResourceManager.GetString("OmissionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приказ.
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Такой приказ уже существует.
        /// </summary>
        public static string OrderExists {
            get {
                return ResourceManager.GetString("OrderExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приказы.
        /// </summary>
        public static string Orders {
            get {
                return ResourceManager.GetString("Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы не выбрали приказы.
        /// </summary>
        public static string OrdersCountZero {
            get {
                return ResourceManager.GetString("OrdersCountZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип приказа.
        /// </summary>
        public static string OrderType {
            get {
                return ResourceManager.GetString("OrderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вывести.
        /// </summary>
        public static string Output {
            get {
                return ResourceManager.GetString("Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вывод ведомости.
        /// </summary>
        public static string OutputStatement {
            get {
                return ResourceManager.GetString("OutputStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Такое взыскание/поощрение уже существует по данному приказу.
        /// </summary>
        public static string PenAndIncExists {
            get {
                return ResourceManager.GetString("PenAndIncExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы не выбрали взыскания/поощрения.
        /// </summary>
        public static string PenAndIncsCountZero {
            get {
                return ResourceManager.GetString("PenAndIncsCountZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Смена/Удаление фото.
        /// </summary>
        public static string PhotoEdit {
            get {
                return ResourceManager.GetString("PhotoEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыть окно смены/удаления фото.
        /// </summary>
        public static string PhotoEditOpen {
            get {
                return ResourceManager.GetString("PhotoEditOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прикрепить.
        /// </summary>
        public static string Pin {
            get {
                return ResourceManager.GetString("Pin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данная практика уже существует.
        /// </summary>
        public static string PracticeExists {
            get {
                return ResourceManager.GetString("PracticeExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данное название практики уже существует.
        /// </summary>
        public static string PracticeNameExists {
            get {
                return ResourceManager.GetString("PracticeNameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Практики.
        /// </summary>
        public static string Practics {
            get {
                return ResourceManager.GetString("Practics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы не выбрали практики.
        /// </summary>
        public static string PracticsCountZero {
            get {
                return ResourceManager.GetString("PracticsCountZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбрать дату защиты.
        /// </summary>
        public static string ProtectDateToolTip {
            get {
                return ResourceManager.GetString("ProtectDateToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Присвоена квалификация.
        /// </summary>
        public static string QualificationAwarded {
            get {
                return ResourceManager.GetString("QualificationAwarded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Такая квалификация уже существует.
        /// </summary>
        public static string QualificationExists {
            get {
                return ResourceManager.GetString("QualificationExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обязательно для заполнения.
        /// </summary>
        public static string RequiredFillIn {
            get {
                return ResourceManager.GetString("RequiredFillIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Успешно сохранено!.
        /// </summary>
        public static string SaveCongrats {
            get {
                return ResourceManager.GetString("SaveCongrats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата выдачи аттестата.
        /// </summary>
        public static string SchoolGraduate {
            get {
                return ResourceManager.GetString("SchoolGraduate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбрать дату выдачи аттестата.
        /// </summary>
        public static string SchoolGraduateToolTip {
            get {
                return ResourceManager.GetString("SchoolGraduateToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название образов. учреждения.
        /// </summary>
        public static string SchoolName {
            get {
                return ResourceManager.GetString("SchoolName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Секретарь.
        /// </summary>
        public static string Secretary {
            get {
                return ResourceManager.GetString("Secretary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Специальность.
        /// </summary>
        public static string Specialization {
            get {
                return ResourceManager.GetString("Specialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата начала обучения.
        /// </summary>
        public static string StartStudyDate {
            get {
                return ResourceManager.GetString("StartStudyDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбрать дату начала обучения.
        /// </summary>
        public static string StartStudyDateToolTip {
            get {
                return ResourceManager.GetString("StartStudyDateToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Студент.
        /// </summary>
        public static string Student {
            get {
                return ResourceManager.GetString("Student", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы не выбрали студента.
        /// </summary>
        public static string StudentCountZero {
            get {
                return ResourceManager.GetString("StudentCountZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Такой студент уже существует.
        /// </summary>
        public static string StudentExists {
            get {
                return ResourceManager.GetString("StudentExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оценки студента.
        /// </summary>
        public static string StudentMarks {
            get {
                return ResourceManager.GetString("StudentMarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пропуски студента.
        /// </summary>
        public static string StudentOmissions {
            get {
                return ResourceManager.GetString("StudentOmissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поощрения/взыскания студента.
        /// </summary>
        public static string StudentPenAndInc {
            get {
                return ResourceManager.GetString("StudentPenAndInc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Студенты.
        /// </summary>
        public static string Students {
            get {
                return ResourceManager.GetString("Students", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверьте наличие студентов в группе, а также их количество.
        /// </summary>
        public static string StudentsError {
            get {
                return ResourceManager.GetString("StudentsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фамилия.
        /// </summary>
        public static string Surname {
            get {
                return ResourceManager.GetString("Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Преподаватель уже прикреплен.
        /// </summary>
        public static string TeacherAlreadyPined {
            get {
                return ResourceManager.GetString("TeacherAlreadyPined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Преподаватель уже преподает данный предмет.
        /// </summary>
        public static string TeacherAlreadyTaught {
            get {
                return ResourceManager.GetString("TeacherAlreadyTaught", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы не выбрали преподавателя.
        /// </summary>
        public static string TeacherCountZero {
            get {
                return ResourceManager.GetString("TeacherCountZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Преподаватель уже существует.
        /// </summary>
        public static string TeacherExists {
            get {
                return ResourceManager.GetString("TeacherExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Преподаватели.
        /// </summary>
        public static string Teachers {
            get {
                return ResourceManager.GetString("Teachers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы не выбрали преподавателей на открепление.
        /// </summary>
        public static string TeachersCountZero {
            get {
                return ResourceManager.GetString("TeachersCountZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Семестр.
        /// </summary>
        public static string Term {
            get {
                return ResourceManager.GetString("Term", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 семестр.
        /// </summary>
        public static string Term1 {
            get {
                return ResourceManager.GetString("Term1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 семестр.
        /// </summary>
        public static string Term2 {
            get {
                return ResourceManager.GetString("Term2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 семестр.
        /// </summary>
        public static string Term3 {
            get {
                return ResourceManager.GetString("Term3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4 семестр.
        /// </summary>
        public static string Term4 {
            get {
                return ResourceManager.GetString("Term4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 семестр.
        /// </summary>
        public static string Term5 {
            get {
                return ResourceManager.GetString("Term5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6 семестр.
        /// </summary>
        public static string Term6 {
            get {
                return ResourceManager.GetString("Term6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7 семестр.
        /// </summary>
        public static string Term7 {
            get {
                return ResourceManager.GetString("Term7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8 семестр.
        /// </summary>
        public static string Term8 {
            get {
                return ResourceManager.GetString("Term8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тема.
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to У данного куратора уже имеются 2 группы, хотите продолжить?.
        /// </summary>
        public static string TooMuchGroups {
            get {
                return ResourceManager.GetString("TooMuchGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открепить.
        /// </summary>
        public static string Unpin {
            get {
                return ResourceManager.GetString("Unpin", resourceCulture);
            }
        }
    }
}
