//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuratorHelper.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CuratorHelperEntities : DbContext
    {
        public CuratorHelperEntities()
            : base("name=CuratorHelperEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AppointedTeacher> AppointedTeachers { get; set; }
        public virtual DbSet<CourseWork> CourseWorks { get; set; }
        public virtual DbSet<Credit> Credits { get; set; }
        public virtual DbSet<DemoExam> DemoExams { get; set; }
        public virtual DbSet<DemoExamName> DemoExamNames { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Discipline> Disciplines { get; set; }
        public virtual DbSet<DisciplineIndex> DisciplineIndexes { get; set; }
        public virtual DbSet<Gender> Genders { get; set; }
        public virtual DbSet<GraduateWork> GraduateWorks { get; set; }
        public virtual DbSet<GraduateWorkType> GraduateWorkTypes { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<Object> Objects { get; set; }
        public virtual DbSet<Omission> Omissions { get; set; }
        public virtual DbSet<OmissionType> OmissionTypes { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<OrderType> OrderTypes { get; set; }
        public virtual DbSet<PenAndInc> PenAndIncs { get; set; }
        public virtual DbSet<PenAndIncType> PenAndIncTypes { get; set; }
        public virtual DbSet<Practice> Practices { get; set; }
        public virtual DbSet<PracticeIndex> PracticeIndexes { get; set; }
        public virtual DbSet<PracticeName> PracticeNames { get; set; }
        public virtual DbSet<Qualification> Qualifications { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Specialization> Specializations { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Teacher> Teachers { get; set; }
        public virtual DbSet<TeacherObjectTaught> TeacherObjectTaughts { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<WorkProgram> WorkPrograms { get; set; }
    }
}
