//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuratorHelper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseWork
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public byte Term { get; set; }
        public System.DateTime FinishDate { get; set; }
        public int DisciplineID { get; set; }
        public byte Mark { get; set; }
        public int StudentID { get; set; }
    
        public virtual Discipline Discipline { get; set; }
        public virtual Student Student { get; set; }
    }
}
