//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuratorHelper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Credit
    {
        public int ID { get; set; }
        public int StudentID { get; set; }
        public int DisciplineID { get; set; }
        public Nullable<int> Term1Mark { get; set; }
        public Nullable<int> Term2Mark { get; set; }
        public Nullable<int> Term3Mark { get; set; }
        public Nullable<int> Term4Mark { get; set; }
        public Nullable<int> Term5Mark { get; set; }
        public Nullable<int> Term6Mark { get; set; }
        public Nullable<int> Term7Mark { get; set; }
        public Nullable<int> Term8Mark { get; set; }
    
        public virtual Discipline Discipline { get; set; }
        public virtual Student Student { get; set; }
    }
}
