//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuratorHelper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Omission
    {
        public int ID { get; set; }
        public int OmissionTypeID { get; set; }
        public Nullable<int> Term1Count { get; set; }
        public Nullable<int> Term2Count { get; set; }
        public Nullable<int> Term3Count { get; set; }
        public Nullable<int> Term4Count { get; set; }
        public Nullable<int> Term5Count { get; set; }
        public Nullable<int> Term6Count { get; set; }
        public Nullable<int> Term7Count { get; set; }
        public Nullable<int> Term8Count { get; set; }
        public Nullable<int> StudentID { get; set; }
    
        public virtual OmissionType OmissionType { get; set; }
        public virtual Student Student { get; set; }
    }
}
