//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuratorHelper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.PenAndIncs = new HashSet<PenAndInc>();
        }
    
        public int ID { get; set; }
        public int OrderTypeID { get; set; }
        public System.DateTime Date { get; set; }
        public int StudentID { get; set; }
        public Nullable<byte> Course { get; set; }
    
        public virtual OrderType OrderType { get; set; }
        public virtual Student Student { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PenAndInc> PenAndIncs { get; set; }
    }
}
