//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuratorHelper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PenAndInc
    {
        public int ID { get; set; }
        public int PenAndIncTypeID { get; set; }
        public string Nature { get; set; }
        public int OrderID { get; set; }
        public int StudentID { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual PenAndIncType PenAndIncType { get; set; }
        public virtual Student Student { get; set; }
    }
}
